### PR TITLE
1.0.7 Channel Names Update

### PR DESCRIPTION
**Pull request by GravityWolfNotAmused**
A lot of people have been asking for a way to update channel names, and I have been saying no for a while. The reason why I didn't want to do this in the first place is that many people will run into the rate limit set by discord, and claim the bot doesn't update frequently enough.

The rate limit set by discord is 2 requests per 10 minutes of time, and I cannot change that, but hey! It does the thing at least some of the time! :100: :+1:

**Documentation changes are located here: #14**

**Release Ready Zip**

If anyone has time to test feel free to let me know if you run into any issues with using ChannelID, and without.

[DiscordPlayerCountBot.zip](https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/files/8065372/DiscordPlayerCountBot.zip)

### CODE REVIEW

**Comment by GravityWolfNotAmused** [comment]
The new test version is meant to fix issues with docker and using channel names.

[DiscordPlayerCountBot.zip](https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/files/8072454/DiscordPlayerCountBot.zip)

**Comment by GravityWolfNotAmused** [comment]
Update to fix the issue where ChannelID was screaming about the range of the id added.

[DiscordPlayerCountBot.zip](https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/files/8073507/DiscordPlayerCountBot.zip)

**Comment by GravityWolfNotAmused** [comment]
Fix for the spam of timeout warnings.

[DiscordPlayerCountBot.zip](https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/files/8074804/DiscordPlayerCountBot.zip)

**Comment by GravityWolfNotAmused** [comment]
After updating to the newest version of DNet and Newtonsoft.Json, I cannot recreate the timeout issue anymore.

[DiscordPlayerCountBot.zip](https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/files/8081224/DiscordPlayerCountBot.zip)

**Comment by GravityWolfNotAmused** [comment]
@Specker how are you feeling about this release? Do you believe it's ready on the docker side? I feel that it's ready for the executable side.

**Comment by Specker** [comment]
I believe everything works as intended and that it can be merged :)

**Comment by GravityWolfNotAmused** [comment]
@Specker I will work on release notes, and executable package tonight and release. Thank you for your work 🥇

**Pull request merged**
