### PR TITLE
Addition to using hostname as IP address inside of config.

### PR DESCRIPTION
**Pull request by GravityWolfNotAmused**
The users can now use `hostname` as their IP address for their server to resolve what their current IP address is for the server. Note the bot, and the server have to be on the same machine to resolve the correct address.

### CODE REVIEW

**Comment by GravityWolfNotAmused** [comment]
Runnable Files are located below.

[DiscordPlayerCountBot.zip](https://github.com/GravityWolfNotAmused/PlayerCountDiscordBot/files/6333298/DiscordPlayerCountBot.zip)

**Comment by Tesch1933** [comment]
Hi, I'm back from holiday and have tried it out straight away.
Unfortunately it did not work for me.

...
_Calling fist update
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array._
...

What and where exactly do I have to enter the "hostname"?

      "botAddress": "XXX",
      
XXX = hostname? ->: name of the DayZ Server? 

I use the "DiscordPlayerCountBot.zip" above
When i enter my current ip everything works fine
I think I just didn't understand what to enter instead of the IP address

**Comment by GravityWolfNotAmused** [comment]
Bot Address should just need to be hostname

**Comment by GravityWolfNotAmused** [comment]
I'll look when I'm off of work

**Comment by GravityWolfNotAmused** [comment]
After looking around, and testing I think you may have messed up your config, please verify that you have it similar below except with your port, discord bot token, and steam API key. Please do not post the bot token, or steam API key.
```json
{
  "_serverInformation": [
    {
      "botName": "VPPTestBot",
      "botAddress": "hostname:27014",
      "discordBotToken": "DiscordTokenHere"
    }
  ],
  "_updateTime": 30,
  "_steamAPIKey": "SteamAPIKeyHere",
  "_isDebug": false,
  "_userConfigNameAsLabel": false
}
```

**Comment by Tesch1933** [comment]
Ok
First problem is fixed.
I just forget to write the port ( ...:27016) after the hostname.
Now the Bot come online @Discord. But it does not show the player count.
it just show: "Starting Bot watching: ...."

I am still not sure what you meen by"hostname"

hostname = Name of the Server?
hostname = Name of the current Windows user?

What you exactly meen with "hostname"?


{
  "_serverInformation": [
    {
      "botName": "Player on Server",
      "botAddress": "??hostname??:27016",
      "discordBotToken": "XXXX"
    }
  ],
  "_updateTime": 60,
  "_steamAPIKey": "XXXXX",
  "_isDebug": false,
  "_userConfigNameAsLabel": false

**Comment by GravityWolfNotAmused** [comment]
When I'm speaking of hostname i simply mean use the word hostname instead of your IP. Like i showed in my json.l, i really mean replace your IP with the word, don't need to look for the system name, or anything like that.

**Comment by Tesch1933** [comment]
Ok
I tested that at the very beginning.
However, that didn't work either, which is why I was unsure.

The Discord-BOT did not display the number of players.

It displays:
"Startong Bot watching: hostname:27016"

These are my current settings:


{
  "_serverInformation": [
    {
      "botName": "Player on Server",
      "botAddress": "hostname:27016",
      "discordBotToken": "XXX"
    }
  ],
  "_updateTime": 30,
  "_steamAPIKey": "XXX",
  "_isDebug": false,
  "_userConfigNameAsLabel": false
}

**Comment by GravityWolfNotAmused** [comment]
I haven't gotten around to it, as i have been busy with life. I did make some changes, but I'm still testing to make sure it works for your use case, I think I know what I might do, but need the time to do accomplish it.

**Pull request merged**
